---
services:
  auth_service_db:
    container_name: auth_service_db
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - web
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - auth-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  auth-data:

networks:
  web:
    external: true
